apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-api
  labels:
    app: book-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-api
  template:
    metadata:
      labels:
        app: book-api
    spec:
      containers:
        - name: book-api
          image: yeng123/book-api
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          
---
apiVersion: v1
kind: Service
metadata:
  name: book-api
spec:
  selector:
    app: book-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30102
  type: NodePort